### PR TITLE
Pass paramaters on language change

### PR DESCRIPTION
**Pull request by vxda**
Hi, I added option to redirect to proper language with parameters passed on.
so that when the url is http://yoursite.com/?someparameter=value&someparameter=value2 
it will redirect to proper language with thoes parameters.

### CODE REVIEW

**Comment by plauclair** [comment]
Thanks for the proposition, it's a very good idea! I'll probably add it with native PW functions (wire("input")->get()) instead and specify the parameter to use though.

**Comment by vxda** [comment]
awesome :) good job with the plugin, it rly makes the difference with seo.

**Comment by plauclair** [comment]
Glad you found this useful! 😄

**Comment by plauclair** [comment]
Also for SEO, it's a good idea to use the meta tag hreflang. :) I think FB uses it too to display content in the right locale, but not 100% sure. https://support.google.com/webmasters/answer/189077?hl=en

**Comment by vxda** [comment]
:+1:  thx for the tip :) implemented on site.

**Comment by plauclair** [comment]
Just a heads up, I still plan on adding this feature, but things got in the way! Soon, my friend!

**Comment by plauclair** [comment]
Hey @vxda, I just got around to implement this. Enjoy!

**Pull request closed without merging**
